/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

/**
 *
 * @author 2022122760117
 */
import control.QuartoAbstractTableModel;
import control.uiManeger;
import javax.swing.JOptionPane;
import  control.uiManeger.JPaneLGradient;
import java.sql.SQLException;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.PersistenceException;

import model.Quarto;

public class CadastrarQuartos extends javax.swing.JDialog {

   private Quarto quartoSelecionado =null;
    private QuartoAbstractTableModel quartoTblModel = null;
            
    public CadastrarQuartos(java.awt.Frame parent, boolean modal) {
        super(parent,true);
        initComponents();
        setSize(775,400);
        setLocation(500,100);
        quartoTblModel = new QuartoAbstractTableModel();
        tabelaQuartos.setModel(quartoTblModel);
         List<Quarto> lista = uiManeger.getInstance().getDomainManeger().ListarQuarto();

        QuartoAbstractTableModel TableModel = (QuartoAbstractTableModel) tabelaQuartos.getModel();
        TableModel.setLista(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popTblQuartos = new javax.swing.JPopupMenu();
        popAdicionar = new javax.swing.JMenuItem();
        popRemover = new javax.swing.JMenuItem();
        jPanel6 = JPaneLGradient.criarPainelDegrade()
        ;
        pnlQuartosCadastrados = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        lblNumQuartos = new javax.swing.JLabel();
        txtNumQuarto = new javax.swing.JTextField();
        cmbTipoQuarto = new javax.swing.JComboBox<>();
        lblTipoQuarto = new javax.swing.JLabel();
        lblDiaria = new javax.swing.JLabel();
        txtDiaria = new javax.swing.JTextField();
        lblCama = new javax.swing.JLabel();
        cmbTipoCama = new javax.swing.JComboBox<>();
        pnlTblQuartos = new javax.swing.JPanel();
        scrollTblQuartos = new javax.swing.JScrollPane();
        tabelaQuartos = new javax.swing.JTable();
        pnlAdicionarRemover = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlCadastrarQuartos = new javax.swing.JPanel();
        lblCadastrarQuartos = new javax.swing.JLabel();

        popAdicionar.setText("Adicionar");
        popAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        popTblQuartos.add(popAdicionar);

        popRemover.setText("Remover");
        popRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        popTblQuartos.add(popRemover);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Quartos");
        setMaximumSize(new java.awt.Dimension(765, 400));
        setMinimumSize(new java.awt.Dimension(765, 400));
        setResizable(false);

        jPanel6.setMaximumSize(new java.awt.Dimension(765, 400));
        jPanel6.setMinimumSize(new java.awt.Dimension(765, 400));
        jPanel6.setPreferredSize(new java.awt.Dimension(765, 400));

        pnlQuartosCadastrados.setOpaque(false);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Quartos Cadastrados");

        javax.swing.GroupLayout pnlQuartosCadastradosLayout = new javax.swing.GroupLayout(pnlQuartosCadastrados);
        pnlQuartosCadastrados.setLayout(pnlQuartosCadastradosLayout);
        pnlQuartosCadastradosLayout.setHorizontalGroup(
            pnlQuartosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuartosCadastradosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlQuartosCadastradosLayout.setVerticalGroup(
            pnlQuartosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuartosCadastradosLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pnlPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        pnlPrincipal.setOpaque(false);

        lblNumQuartos.setBackground(new java.awt.Color(255, 255, 255));
        lblNumQuartos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumQuartos.setForeground(new java.awt.Color(0, 0, 0));
        lblNumQuartos.setText("Núm. Quarto");

        cmbTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suite", "Casal", "Solteiro" }));

        lblTipoQuarto.setBackground(new java.awt.Color(255, 255, 255));
        lblTipoQuarto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipoQuarto.setForeground(new java.awt.Color(0, 0, 0));
        lblTipoQuarto.setText("Tipo do Quarto");

        lblDiaria.setBackground(new java.awt.Color(255, 255, 255));
        lblDiaria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaria.setForeground(new java.awt.Color(0, 0, 0));
        lblDiaria.setText("Preço Diária");

        lblCama.setBackground(new java.awt.Color(255, 255, 255));
        lblCama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCama.setForeground(new java.awt.Color(0, 0, 0));
        lblCama.setText("Cama");

        cmbTipoCama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casal", "King" }));

        pnlTblQuartos.setOpaque(false);

        tabelaQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número do Quarto", "Tipo do Quarto", "Cama", "Preço Diária"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaQuartos.setComponentPopupMenu(popTblQuartos);
        scrollTblQuartos.setViewportView(tabelaQuartos);

        javax.swing.GroupLayout pnlTblQuartosLayout = new javax.swing.GroupLayout(pnlTblQuartos);
        pnlTblQuartos.setLayout(pnlTblQuartosLayout);
        pnlTblQuartosLayout.setHorizontalGroup(
            pnlTblQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblQuartosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollTblQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTblQuartosLayout.setVerticalGroup(
            pnlTblQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTblQuartos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAdicionarRemover.setOpaque(false);

        btAdicionar.setBackground(new java.awt.Color(153, 255, 153));
        btAdicionar.setForeground(new java.awt.Color(0, 0, 0));
        btAdicionar.setText("Adicionar");
        btAdicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarbtAdicionarActionPerformed(evt);
            }
        });

        btRemover.setBackground(new java.awt.Color(255, 102, 102));
        btRemover.setForeground(new java.awt.Color(0, 0, 0));
        btRemover.setText("Remover");
        btRemover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(255, 204, 102));
        btAlterar.setForeground(new java.awt.Color(0, 0, 0));
        btAlterar.setText("Alterar");
        btAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarbtAdicionarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(204, 204, 255));
        btLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btLimpar.setText("Limpar");
        btLimpar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdicionarRemoverLayout = new javax.swing.GroupLayout(pnlAdicionarRemover);
        pnlAdicionarRemover.setLayout(pnlAdicionarRemoverLayout);
        pnlAdicionarRemoverLayout.setHorizontalGroup(
            pnlAdicionarRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicionarRemoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAdicionarRemoverLayout.setVerticalGroup(
            pnlAdicionarRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdicionarRemoverLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlAdicionarRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btRemover)
                    .addComponent(btLimpar)
                    .addComponent(btAlterar))
                .addGap(15, 15, 15))
        );

        jPanel1.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Selecionar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiaria)
                            .addComponent(lblCama)
                            .addComponent(lblTipoQuarto)
                            .addComponent(lblNumQuartos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoQuarto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoCama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumQuarto)
                            .addComponent(txtDiaria, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlAdicionarRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTblQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumQuartos)
                            .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoQuarto))
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCama)
                            .addComponent(cmbTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaria)
                            .addComponent(txtDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlAdicionarRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlTblQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlCadastrarQuartos.setOpaque(false);

        lblCadastrarQuartos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCadastrarQuartos.setForeground(new java.awt.Color(0, 51, 255));
        lblCadastrarQuartos.setText("Gerenciar Quartos");

        javax.swing.GroupLayout pnlCadastrarQuartosLayout = new javax.swing.GroupLayout(pnlCadastrarQuartos);
        pnlCadastrarQuartos.setLayout(pnlCadastrarQuartosLayout);
        pnlCadastrarQuartosLayout.setHorizontalGroup(
            pnlCadastrarQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarQuartosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCadastrarQuartos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCadastrarQuartosLayout.setVerticalGroup(
            pnlCadastrarQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarQuartosLayout.createSequentialGroup()
                .addComponent(lblCadastrarQuartos)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlCadastrarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(pnlQuartosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCadastrarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlQuartosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int index = tabelaQuartos.getSelectedRow();
        quartoSelecionado= quartoTblModel.getQuarto(index);
        
       try {
           uiManeger.getInstance().getDomainManeger().excluir(quartoSelecionado);
           quartoTblModel.remover(index);
       } catch (SQLException | ClassNotFoundException ex) {
           Logger.getLogger(CadastrarQuartos.class.getName()).log(Level.SEVERE, null, ex);
       }
       catch (PersistenceException ex) {
        Logger.getLogger(CadastrarQuartos.class.getName()).log(Level.SEVERE, null, ex);
       }
        JOptionPane.showMessageDialog(this, "Erro ao remover quarto: Violação de restrição.", "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
         
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAlterarbtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarbtAdicionarActionPerformed
        try {
        int numQuarto = Integer.parseInt(txtNumQuarto.getText());
        String tipoQuarto = cmbTipoQuarto.getSelectedItem().toString();
        String cama = cmbTipoCama.getSelectedItem().toString();
        double valorDiaria = Double.parseDouble(txtDiaria.getText());

        // Verifica se algum campo está vazio
        if (txtNumQuarto.getText().isEmpty() || tipoQuarto.isEmpty() || cama.isEmpty() || txtDiaria.getText().isEmpty()) {
            throw new IllegalArgumentException("Por favor, preencha todos os campos.");
        }

        

        if (quartoSelecionado != null) {
            // Verifica se o número do quarto foi alterado
            if (numQuarto != quartoSelecionado.getNumQuarto()) {
                throw new IllegalArgumentException("Não é permitido alterar o número do quarto.");
            }

            // Altera o quarto no gerenciador de domínio
            uiManeger.getInstance().getDomainManeger().alterarQuarto(numQuarto, tipoQuarto, cama, valorDiaria);

            // Exibe mensagem de sucesso
            JOptionPane.showMessageDialog(this, "Quarto " + quartoSelecionado.getNumQuarto() + " alterado com sucesso.", "Cadastro Cliente", JOptionPane.INFORMATION_MESSAGE);

            // Atualiza a tabela de quartos
            atualizarTabelaQuartos();
        } else {
            Quarto qt =uiManeger.getInstance().getDomainManeger().inserirQuarto(numQuarto, tipoQuarto, cama, valorDiaria);
            quartoTblModel.adicionar(qt);
            JOptionPane.showMessageDialog(this, "Quarto " + qt.getNumQuarto() + " inserido com sucesso.", "Cadastro Cliente", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Por favor, insira um número válido para o número do quarto e um valor válido para a diária.", "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btAlterarbtAdicionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         QuartoAbstractTableModel model = (QuartoAbstractTableModel) tabelaQuartos.getModel();

        int linha = tabelaQuartos.getSelectedRow();
        
        if (linha >= 0) {

            quartoSelecionado = quartoTblModel.getQuarto(linha);
        }

        if (linha != -1) {

            String numQuarto = model.getValueAt(linha, 0).toString();
            String tipoQuarto = model.getValueAt(linha, 1).toString();
            String cama= model.getValueAt(linha, 2).toString();
            String diaria = model.getValueAt(linha, 3).toString();

            Quarto quarto = new Quarto();
            
            quarto.setNumQuarto(Integer.parseInt(numQuarto));
            quarto.setTipoQuarto(tipoQuarto);
            quarto.setCama(cama);
            quarto.setValorDiaria(Double.parseDouble(diaria));

            preencherCampos(quarto);
        } else {
            
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma linha primeiro.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

  private void atualizarTabelaQuartos() {
        List<Quarto> lista = uiManeger.getInstance().getDomainManeger().ListarQuarto();
        quartoTblModel.setLista(lista);
        quartoTblModel.fireTableDataChanged(); 
    }
   private void limparCampos()
   {
       txtNumQuarto.setText("");
       txtDiaria.setText("");
       cmbTipoCama.setSelectedIndex(0);
       cmbTipoQuarto.setSelectedIndex(0);
       quartoSelecionado=null;
   }  
   
  private void preencherCampos(Quarto quarto) {
    txtNumQuarto.setText(String.valueOf(quarto.getNumQuarto()));
    cmbTipoQuarto.setSelectedItem(quarto.getTipoQuarto());
    cmbTipoCama.setSelectedItem(quarto.getCama());
    txtDiaria.setText(String.valueOf(quarto.getValorDiaria()));
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox<String> cmbTipoCama;
    private javax.swing.JComboBox<String> cmbTipoQuarto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCadastrarQuartos;
    private javax.swing.JLabel lblCama;
    private javax.swing.JLabel lblDiaria;
    private javax.swing.JLabel lblNumQuartos;
    private javax.swing.JLabel lblTipoQuarto;
    private javax.swing.JPanel pnlAdicionarRemover;
    private javax.swing.JPanel pnlCadastrarQuartos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlQuartosCadastrados;
    private javax.swing.JPanel pnlTblQuartos;
    private javax.swing.JMenuItem popAdicionar;
    private javax.swing.JMenuItem popRemover;
    private javax.swing.JPopupMenu popTblQuartos;
    private javax.swing.JScrollPane scrollTblQuartos;
    private javax.swing.JTable tabelaQuartos;
    private javax.swing.JTextField txtDiaria;
    private javax.swing.JTextField txtNumQuarto;
    // End of variables declaration//GEN-END:variables
}
