/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

/**
 *
 * @author 2022122760117
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import  viewer.TelaPrincipal.JPaneLGradient;
import viewer.TelaPrincipal.TableUtilidades;

public class CadastrarQuartos extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarQuartoss
     * @param parent
     */
    public CadastrarQuartos(java.awt.Frame parent, boolean modal) {
        super(parent,true);
        initComponents();
        setSize(765,400);
        setLocation(500,100);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popTblQuartos = new javax.swing.JPopupMenu();
        popAdicionar = new javax.swing.JMenuItem();
        popRemover = new javax.swing.JMenuItem();
        jPanel6 = JPaneLGradient.criarPainelDegrade()
        ;
        pnlQuartosCadastrados = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        lblNumQuartos = new javax.swing.JLabel();
        txtNumQuarto = new javax.swing.JTextField();
        cmbTipoQuarto = new javax.swing.JComboBox<>();
        lblTipoQuarto = new javax.swing.JLabel();
        lblDiaria = new javax.swing.JLabel();
        txtDiaria = new javax.swing.JTextField();
        lblCama = new javax.swing.JLabel();
        cmbTipoCama = new javax.swing.JComboBox<>();
        pnlTblQuartos = new javax.swing.JPanel();
        scrollTblQuartos = new javax.swing.JScrollPane();
        tabelaQuartos = new javax.swing.JTable();
        pnlAdicionarRemover = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        pnlCadastrarQuartos = new javax.swing.JPanel();
        lblCadastrarQuartos = new javax.swing.JLabel();

        popAdicionar.setText("Adicionar");
        popAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        popTblQuartos.add(popAdicionar);

        popRemover.setText("Remover");
        popRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        popTblQuartos.add(popRemover);

        setMaximumSize(new java.awt.Dimension(765, 400));
        setMinimumSize(new java.awt.Dimension(765, 400));
        setPreferredSize(new java.awt.Dimension(765, 400));
        setResizable(false);

        jPanel6.setMaximumSize(new java.awt.Dimension(765, 400));
        jPanel6.setMinimumSize(new java.awt.Dimension(765, 400));
        jPanel6.setPreferredSize(new java.awt.Dimension(765, 400));

        pnlQuartosCadastrados.setOpaque(false);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quartos Cadastrados");

        javax.swing.GroupLayout pnlQuartosCadastradosLayout = new javax.swing.GroupLayout(pnlQuartosCadastrados);
        pnlQuartosCadastrados.setLayout(pnlQuartosCadastradosLayout);
        pnlQuartosCadastradosLayout.setHorizontalGroup(
            pnlQuartosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuartosCadastradosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlQuartosCadastradosLayout.setVerticalGroup(
            pnlQuartosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuartosCadastradosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        pnlPrincipal.setOpaque(false);

        lblNumQuartos.setBackground(new java.awt.Color(255, 255, 255));
        lblNumQuartos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumQuartos.setForeground(new java.awt.Color(255, 255, 255));
        lblNumQuartos.setText("Núm. Quarto");

        txtNumQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumQuartoActionPerformed(evt);
            }
        });

        cmbTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suite", "Casal", "Solteiro" }));

        lblTipoQuarto.setBackground(new java.awt.Color(255, 255, 255));
        lblTipoQuarto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipoQuarto.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoQuarto.setText("Tipo do Quarto");

        lblDiaria.setBackground(new java.awt.Color(255, 255, 255));
        lblDiaria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaria.setForeground(new java.awt.Color(255, 255, 255));
        lblDiaria.setText("Preço Diária");

        txtDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiariaActionPerformed(evt);
            }
        });

        lblCama.setBackground(new java.awt.Color(255, 255, 255));
        lblCama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCama.setForeground(new java.awt.Color(255, 255, 255));
        lblCama.setText("Cama");

        cmbTipoCama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casal", "King" }));

        pnlTblQuartos.setOpaque(false);

        tabelaQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número do Quarto", "Tipo do Quarto", "Cama", "Preço Diária"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaQuartos.setComponentPopupMenu(popTblQuartos);
        scrollTblQuartos.setViewportView(tabelaQuartos);

        javax.swing.GroupLayout pnlTblQuartosLayout = new javax.swing.GroupLayout(pnlTblQuartos);
        pnlTblQuartos.setLayout(pnlTblQuartosLayout);
        pnlTblQuartosLayout.setHorizontalGroup(
            pnlTblQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblQuartosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollTblQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTblQuartosLayout.setVerticalGroup(
            pnlTblQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTblQuartos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAdicionarRemover.setOpaque(false);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdicionarRemoverLayout = new javax.swing.GroupLayout(pnlAdicionarRemover);
        pnlAdicionarRemover.setLayout(pnlAdicionarRemoverLayout);
        pnlAdicionarRemoverLayout.setHorizontalGroup(
            pnlAdicionarRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicionarRemoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemover)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlAdicionarRemoverLayout.setVerticalGroup(
            pnlAdicionarRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdicionarRemoverLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlAdicionarRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btRemover))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiaria)
                            .addComponent(lblCama)
                            .addComponent(lblTipoQuarto)
                            .addComponent(lblNumQuartos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoQuarto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoCama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumQuarto)
                            .addComponent(txtDiaria, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlAdicionarRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnlTblQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumQuartos)
                            .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoQuarto))
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCama)
                            .addComponent(cmbTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaria)
                            .addComponent(txtDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlAdicionarRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlTblQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlCadastrarQuartos.setOpaque(false);

        lblCadastrarQuartos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCadastrarQuartos.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastrarQuartos.setText("Cadastrar Quartos");

        javax.swing.GroupLayout pnlCadastrarQuartosLayout = new javax.swing.GroupLayout(pnlCadastrarQuartos);
        pnlCadastrarQuartos.setLayout(pnlCadastrarQuartosLayout);
        pnlCadastrarQuartosLayout.setHorizontalGroup(
            pnlCadastrarQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarQuartosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCadastrarQuartos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCadastrarQuartosLayout.setVerticalGroup(
            pnlCadastrarQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrarQuartosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCadastrarQuartos)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlCadastrarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlQuartosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCadastrarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlQuartosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        TableUtilidades.removerLinhaSelecionada((DefaultTableModel) tabelaQuartos.getModel(), tabelaQuartos);
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
         DefaultTableModel tblQuartos = (DefaultTableModel) tabelaQuartos.getModel();
    Object[] dados = {
        Integer.parseInt(txtNumQuarto.getText()),
        cmbTipoQuarto.getSelectedItem().toString(),
        cmbTipoCama.getSelectedItem().toString(),
        Double.parseDouble(txtDiaria.getText())
    };
    tblQuartos.addRow(dados);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void txtDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiariaActionPerformed

    private void txtNumQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumQuartoActionPerformed

  
      
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox<String> cmbTipoCama;
    private javax.swing.JComboBox<String> cmbTipoQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblCadastrarQuartos;
    private javax.swing.JLabel lblCama;
    private javax.swing.JLabel lblDiaria;
    private javax.swing.JLabel lblNumQuartos;
    private javax.swing.JLabel lblTipoQuarto;
    private javax.swing.JPanel pnlAdicionarRemover;
    private javax.swing.JPanel pnlCadastrarQuartos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlQuartosCadastrados;
    private javax.swing.JPanel pnlTblQuartos;
    private javax.swing.JMenuItem popAdicionar;
    private javax.swing.JMenuItem popRemover;
    private javax.swing.JPopupMenu popTblQuartos;
    private javax.swing.JScrollPane scrollTblQuartos;
    private javax.swing.JTable tabelaQuartos;
    private javax.swing.JTextField txtDiaria;
    private javax.swing.JTextField txtNumQuarto;
    // End of variables declaration//GEN-END:variables
}
